create schema if not exists private;

create table if not exists private.ai_api_keys (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 80),
  key_prefix text not null unique check (char_length(key_prefix) between 8 and 32),
  key_hash text not null unique check (key_hash ~ '^[0-9a-f]{64}$'),
  status text not null default 'active' check (status in ('active', 'revoked')),
  rate_limit_per_minute integer not null default 60 check (rate_limit_per_minute between 1 and 10000),
  rate_limit_per_day integer not null default 5000 check (rate_limit_per_day between 1 and 10000000),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  revoked_by uuid references public.profiles(id),
  last_used_at timestamptz
);

create table if not exists private.ai_api_rate_counters (
  key_id uuid not null references private.ai_api_keys(id) on delete cascade,
  bucket_type text not null check (bucket_type in ('minute', 'day')),
  bucket_start timestamptz not null,
  request_count integer not null default 0 check (request_count >= 0),
  primary key (key_id, bucket_type, bucket_start)
);

create table if not exists private.ai_api_request_logs (
  id bigint generated by default as identity primary key,
  request_id uuid not null,
  key_id uuid references private.ai_api_keys(id) on delete set null,
  endpoint text not null,
  method text not null,
  query_summary text,
  status_code integer not null,
  error_code text,
  duration_ms integer not null default 0 check (duration_ms >= 0),
  created_at timestamptz not null default now()
);

create index if not exists ai_api_request_logs_key_created_idx
  on private.ai_api_request_logs (key_id, created_at desc);
create index if not exists ai_api_request_logs_created_idx
  on private.ai_api_request_logs (created_at desc);

alter table private.ai_api_keys enable row level security;
alter table private.ai_api_rate_counters enable row level security;
alter table private.ai_api_request_logs enable row level security;

revoke all on private.ai_api_keys from public, anon, authenticated;
revoke all on private.ai_api_rate_counters from public, anon, authenticated;
revoke all on private.ai_api_request_logs from public, anon, authenticated;
grant usage on schema private to service_role;
grant select, insert, update, delete on private.ai_api_keys to service_role;
grant select, insert, update, delete on private.ai_api_rate_counters to service_role;
grant select, insert, update, delete on private.ai_api_request_logs to service_role;
grant usage, select on sequence private.ai_api_request_logs_id_seq to service_role;

create or replace function public.authorize_ai_api_request(
  p_key_hash text,
  p_endpoint text,
  p_method text
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_key private.ai_api_keys%rowtype;
  v_now timestamptz := clock_timestamp();
  v_minute_start timestamptz := date_trunc('minute', v_now);
  v_day_start timestamptz := date_trunc('day', v_now at time zone 'UTC') at time zone 'UTC';
  v_minute_count integer := 0;
  v_day_count integer := 0;
  v_retry_after integer := 0;
begin
  select * into v_key
  from private.ai_api_keys
  where key_hash = lower(trim(p_key_hash))
  for update;

  if not found or v_key.status <> 'active' then
    return jsonb_build_object('allowed', false, 'reason', 'INVALID_API_KEY');
  end if;

  select request_count into v_minute_count
  from private.ai_api_rate_counters
  where key_id = v_key.id
    and bucket_type = 'minute'
    and bucket_start = v_minute_start;
  v_minute_count := coalesce(v_minute_count, 0);

  select request_count into v_day_count
  from private.ai_api_rate_counters
  where key_id = v_key.id
    and bucket_type = 'day'
    and bucket_start = v_day_start;
  v_day_count := coalesce(v_day_count, 0);

  if v_minute_count >= v_key.rate_limit_per_minute then
    v_retry_after := greatest(1, ceil(extract(epoch from (v_minute_start + interval '1 minute' - v_now)))::integer);
    return jsonb_build_object(
      'allowed', false,
      'reason', 'RATE_LIMIT_EXCEEDED',
      'scope', 'minute',
      'retry_after', v_retry_after,
      'key_id', v_key.id,
      'key_name', v_key.name,
      'rate_limit_per_minute', v_key.rate_limit_per_minute,
      'rate_limit_per_day', v_key.rate_limit_per_day
    );
  end if;

  if v_day_count >= v_key.rate_limit_per_day then
    v_retry_after := greatest(1, ceil(extract(epoch from (v_day_start + interval '1 day' - v_now)))::integer);
    return jsonb_build_object(
      'allowed', false,
      'reason', 'RATE_LIMIT_EXCEEDED',
      'scope', 'day',
      'retry_after', v_retry_after,
      'key_id', v_key.id,
      'key_name', v_key.name,
      'rate_limit_per_minute', v_key.rate_limit_per_minute,
      'rate_limit_per_day', v_key.rate_limit_per_day
    );
  end if;

  insert into private.ai_api_rate_counters (key_id, bucket_type, bucket_start, request_count)
  values (v_key.id, 'minute', v_minute_start, 1)
  on conflict (key_id, bucket_type, bucket_start)
  do update set request_count = private.ai_api_rate_counters.request_count + 1
  returning request_count into v_minute_count;

  insert into private.ai_api_rate_counters (key_id, bucket_type, bucket_start, request_count)
  values (v_key.id, 'day', v_day_start, 1)
  on conflict (key_id, bucket_type, bucket_start)
  do update set request_count = private.ai_api_rate_counters.request_count + 1
  returning request_count into v_day_count;

  update private.ai_api_keys
  set last_used_at = v_now
  where id = v_key.id;

  return jsonb_build_object(
    'allowed', true,
    'key_id', v_key.id,
    'key_name', v_key.name,
    'rate_limit_per_minute', v_key.rate_limit_per_minute,
    'rate_limit_per_day', v_key.rate_limit_per_day,
    'minute_count', v_minute_count,
    'day_count', v_day_count,
    'minute_remaining', greatest(0, v_key.rate_limit_per_minute - v_minute_count),
    'day_remaining', greatest(0, v_key.rate_limit_per_day - v_day_count)
  );
end;
$$;

create or replace function public.list_ai_api_keys()
returns table (
  id uuid,
  name text,
  key_prefix text,
  status text,
  rate_limit_per_minute integer,
  rate_limit_per_day integer,
  created_by uuid,
  created_at timestamptz,
  revoked_at timestamptz,
  last_used_at timestamptz
)
language sql
security invoker
set search_path = ''
as $$
  select
    k.id,
    k.name,
    k.key_prefix,
    k.status,
    k.rate_limit_per_minute,
    k.rate_limit_per_day,
    k.created_by,
    k.created_at,
    k.revoked_at,
    k.last_used_at
  from private.ai_api_keys k
  order by k.created_at desc;
$$;

create or replace function public.create_ai_api_key(
  p_name text,
  p_key_prefix text,
  p_key_hash text,
  p_created_by uuid,
  p_rate_limit_per_minute integer default 60,
  p_rate_limit_per_day integer default 5000
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_key private.ai_api_keys%rowtype;
begin
  insert into private.ai_api_keys (
    name,
    key_prefix,
    key_hash,
    created_by,
    rate_limit_per_minute,
    rate_limit_per_day
  ) values (
    trim(p_name),
    trim(p_key_prefix),
    lower(trim(p_key_hash)),
    p_created_by,
    p_rate_limit_per_minute,
    p_rate_limit_per_day
  )
  returning * into v_key;

  return jsonb_build_object(
    'id', v_key.id,
    'name', v_key.name,
    'key_prefix', v_key.key_prefix,
    'status', v_key.status,
    'rate_limit_per_minute', v_key.rate_limit_per_minute,
    'rate_limit_per_day', v_key.rate_limit_per_day,
    'created_at', v_key.created_at,
    'last_used_at', v_key.last_used_at
  );
end;
$$;

create or replace function public.revoke_ai_api_key(
  p_id uuid,
  p_revoked_by uuid
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_updated integer;
begin
  update private.ai_api_keys
  set
    status = 'revoked',
    revoked_at = now(),
    revoked_by = p_revoked_by
  where id = p_id and status = 'active';
  get diagnostics v_updated = row_count;
  return v_updated = 1;
end;
$$;

create or replace function public.record_ai_api_request(
  p_request_id uuid,
  p_key_id uuid,
  p_endpoint text,
  p_method text,
  p_query_summary text,
  p_status_code integer,
  p_error_code text,
  p_duration_ms integer
)
returns void
language sql
security invoker
set search_path = ''
as $$
  insert into private.ai_api_request_logs (
    request_id,
    key_id,
    endpoint,
    method,
    query_summary,
    status_code,
    error_code,
    duration_ms
  ) values (
    p_request_id,
    p_key_id,
    left(p_endpoint, 200),
    left(p_method, 16),
    left(p_query_summary, 500),
    p_status_code,
    nullif(left(p_error_code, 80), ''),
    greatest(p_duration_ms, 0)
  );
$$;

revoke all on function public.authorize_ai_api_request(text, text, text) from public, anon, authenticated;
revoke all on function public.list_ai_api_keys() from public, anon, authenticated;
revoke all on function public.create_ai_api_key(text, text, text, uuid, integer, integer) from public, anon, authenticated;
revoke all on function public.revoke_ai_api_key(uuid, uuid) from public, anon, authenticated;
revoke all on function public.record_ai_api_request(uuid, uuid, text, text, text, integer, text, integer) from public, anon, authenticated;

grant execute on function public.authorize_ai_api_request(text, text, text) to service_role;
grant execute on function public.list_ai_api_keys() to service_role;
grant execute on function public.create_ai_api_key(text, text, text, uuid, integer, integer) to service_role;
grant execute on function public.revoke_ai_api_key(uuid, uuid) to service_role;
grant execute on function public.record_ai_api_request(uuid, uuid, text, text, text, integer, text, integer) to service_role;
