alter table public.answer_drafts
  add column if not exists request_type text not null default 'edit',
  add column if not exists request_reason text,
  add column if not exists original_json jsonb,
  add column if not exists updated_at timestamptz not null default now();

alter table public.answer_drafts
  drop constraint if exists answer_drafts_status_check;

update public.answer_drafts
set status = case when status = 'pending' then 'unprocessed' else 'processed' end;

alter table public.answer_drafts
  alter column status set default 'unprocessed';

alter table public.answer_drafts
  add constraint answer_drafts_status_check
  check (status = any (array['unprocessed'::text, 'processed'::text]));

alter table public.answer_drafts
  drop constraint if exists answer_drafts_request_type_check;

alter table public.answer_drafts
  add constraint answer_drafts_request_type_check
  check (request_type = any (array['edit'::text, 'supplement'::text, 'new_problem'::text]));

create index if not exists answer_drafts_status_created_idx
  on public.answer_drafts (status, created_at desc);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  image_key text,
  is_pinned boolean not null default false,
  status text not null default 'published'
    check (status = any (array['published'::text, 'archived'::text])),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create index if not exists announcements_status_sort_idx
  on public.announcements (status, is_pinned desc, created_at desc);

create index if not exists announcements_created_by_idx
  on public.announcements (created_by);

create table if not exists public.announcement_reads (
  announcement_id bigint not null references public.announcements(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (announcement_id, user_id)
);

create index if not exists announcement_reads_user_idx
  on public.announcement_reads (user_id, read_at desc);

alter table public.announcements enable row level security;
alter table public.announcement_reads enable row level security;

revoke all on table public.announcements from public, anon, authenticated;
revoke all on table public.announcement_reads from public, anon, authenticated;
grant select, insert, update, delete on table public.announcements to service_role;
grant select, insert, update, delete on table public.announcement_reads to service_role;
grant usage, select on sequence public.announcements_id_seq to service_role;
